"""add max_sales to subscription_plans

Revision ID: 1d6e1c1c04e4
Revises: a9a81dae3014
Create Date: 2026-07-12 20:21:30.574455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6e1c1c04e4'
down_revision: Union[str, Sequence[str], None] = 'a9a81dae3014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'business_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.add_column('subscription_plans', sa.Column('max_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'max_sales')
    op.drop_constraint(None, 'business_subscriptions', type_='foreignkey')
    # ### end Alembic commands ###
