"""add max_sales to subscription_plans

Revision ID: 46b12b4dbccd
Revises: 1d6e1c1c04e4
Create Date: 2026-07-12 20:31:42.550329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b12b4dbccd'
down_revision: Union[str, Sequence[str], None] = '1d6e1c1c04e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
