"""add max_sales to subscription_plans

Revision ID: 4a3b22bd4646
Revises: cad9a66d87b0
Create Date: 2026-07-14 01:23:21.601855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3b22bd4646'
down_revision: Union[str, Sequence[str], None] = 'cad9a66d87b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'full_name')
    # ### end Alembic commands ###
