"""add timestamps to all tables

Revision ID: a9a81dae3014
Revises: 800c27df680d
Create Date: 2026-07-12 11:15:33.298144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a81dae3014'
down_revision: Union[str, Sequence[str], None] = '800c27df680d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'created_at')
    op.drop_column('business_settings', 'created_at')
    # ### end Alembic commands ###
