"""add max_sales to subscription_plans

Revision ID: cad9a66d87b0
Revises: 46b12b4dbccd
Create Date: 2026-07-12 20:35:42.530972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9a66d87b0'
down_revision: Union[str, Sequence[str], None] = '46b12b4dbccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('max_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'max_sales')
    # ### end Alembic commands ###
